#!/usr/bin/env python3
"""Install a portable skill and non-destructive project instruction bridges."""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

START = "<!-- repo-context:start -->"
END = "<!-- repo-context:end -->"
BLOCK = f"""{START}
## Repository context

For work in this repository, read `.ai/agents.md` when it exists and follow
`.agents/skills/repo-context/SKILL.md`. Load only the context relevant to the task.
Before completing code changes, reconcile affected `.ai` module, feature, pattern,
and architecture context with the code; update `.ai/context-map.json` for new or
removed source areas and validate it with the bundled checker. If no context
change is needed, report the reason. Preserve unrelated edits and repository rules.
For read-only tasks, report context drift without editing files. If `.ai` is absent,
initialize it only when setup is requested; start at Step 0 and complete the sequence.
For generation and maintenance, read the applicable full original prompts under
`.agents/skills/repo-context/prompts/` as routed by SKILL.md. Preserve their detailed
templates, walkthrough requirements, and verification checklists.
{END}
"""


def install(repo: Path, claude: bool = False) -> dict:
    repo = repo.resolve(strict=True)
    if not repo.is_dir():
        raise ValueError("Project root must be a directory")
    origin = Path(__file__).resolve().parents[1]
    target = repo / ".agents/skills/repo-context"
    if not target.resolve().is_relative_to(repo):
        raise ValueError("Skill destination resolves outside the project")
    copies = []
    for source in sorted(origin.rglob("*")):
        if not source.is_file() or "__pycache__" in source.parts or source.suffix == ".pyc":
            continue
        if source.is_symlink():
            raise ValueError(f"Skill includes a symlink: {source}")
        destination = target / source.relative_to(origin)
        if not destination.resolve().is_relative_to(repo):
            raise ValueError(f"Destination resolves outside project: {destination}")
        if destination.exists():
            if destination.read_bytes() != source.read_bytes():
                raise ValueError(f"Existing skill file differs; reconcile manually: {destination}")
        else:
            copies.append((source, destination))

    instructions = []
    for name in ["AGENTS.md"] + (["CLAUDE.md"] if claude else []):
        path = repo / name
        if path.is_symlink():
            raise ValueError(f"Instruction file is a symlink; reconcile manually: {path}")
        current = path.read_text() if path.exists() else ""
        if START in current or END in current:
            if current.count(START) != 1 or current.count(END) != 1:
                raise ValueError(f"Malformed repo-context markers: {path}")
            first, last = current.index(START), current.index(END) + len(END)
            if first >= last or current[first:last] != BLOCK.rstrip():
                raise ValueError(f"Existing repo-context rule differs; reconcile manually: {path}")
            continue
        instructions.append((path, current + ("\n\n" if current else "") + BLOCK))

    # Preflight every conflict before modifying the project.
    for source, destination in copies:
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    for path, content in instructions:
        path.write_text(content)
    return {"skill": str(target), "copied_files": len(copies),
            "instruction_files_updated": [str(p) for p, _ in instructions],
            "next": "Execute SKILL.md generation phases starting at Step 0; context is not generated by this installer."}


def main():
    import json
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, required=True)
    parser.add_argument("--claude", action="store_true", help="Also add the bridge to CLAUDE.md")
    args = parser.parse_args()
    try:
        print(json.dumps(install(args.repo, args.claude), indent=2))
    except (ValueError, OSError) as error:
        parser.exit(2, f"Install failed: {error}\n")


if __name__ == "__main__":
    main()
